name: Web Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automation-test:
    runs-on: ubuntu-latest

    steps:
    # download repo
    - uses: actions/checkout@v3
    
    # Setup Java
    - name: Set up JDK 11
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '11'
        distribution: 'temurin'

    # install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v2.1.0
       with:
          chrome-version: latest # Ganti dengan 'stable' untuk versi stabil
          chrome-options: '--headless' #(Jika ingin menjalankan Chrome dalam mode headless)
          install-chromedriver: # optional
       

    # setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew 

    # Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew cucumber
          
          
