name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # download repo
    - uses: actions/checkout@v4

    # Setup Java
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v2.1.0

    # setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew

    # Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew cucumber
          
          
